CHN:
  base:
    - [plus, relation, 270056] # China
  perspectives:
    CHN:
      # China's additional claims in the Sino-Indian border dispute
      - [plus, relation, 7935380] # Trans-Karakoram Tract
      - [plus, relation, 2713466] # Demchok sector
      - [plus, relation, 2713483] # Gue-Kaurik
      - [plus, relation, 2713485] # Shipki La
      - [plus, relation, 2713676] # Nilang-Jadhang
      - [plus, relation, 2713484] # Barahoti (Wu-Je)
      - [plus, relation, 3202329] # Arunachal Pradesh (South Tibet)
    IND:
      # India's claims in the Sino-Indian border dispute
      - [minus, relation, 7935380] # Trans-Karakoram Tract
      - [minus, relation, 2713465] # Aksai Chin
      - [minus, relation, 2713466] # Demchok sector
    PAK:
      # Pakistan disclaims the Demchok sector, which is claimed by China
      - [plus, relation, 2713466] # Demchok sector
  interior-points:
    CHN:
      - [79.18, 35.15] # Aksai Chin
      - [76.32, 36.09] # Trans-Karakoram Tract

IND:
  base:
    - [plus, relation, 304716] # India
  perspectives:
    IND:
      # India's additional claims in the Sino-Indian border dispute
      - [plus, relation, 7935380] # Trans-Karakoram Tract
      - [plus, relation, 2713465] # Aksai Chin
      - [plus, relation, 2713466] # Demchok sector
      # India's claims on "Pakistan-occupied Kashmir"
      - [plus, relation, 13414393] # Pakistani-Administered Kashmir
    PAK:
      # Pakistan's claims on "Indian-occupied Kashmir"
      - [minus, relation, 5515045] # Ladakh
      - [minus, relation, 1943188] # Jammu and Kashmir
    CHN:
      # China's claims in the Sino-Indian border dispute
      - [minus, relation, 7935380] # Trans-Karakoram Tract
      - [minus, relation, 2713466] # Demchok sector
      - [minus, relation, 2713483] # Gue-Kaurik
      - [minus, relation, 2713485] # Shipki La
      - [minus, relation, 2713676] # Nilang-Jadhang
      - [minus, relation, 2713484] # Wu-Je (Barahoti)
      - [minus, relation, 3202329] # South Tibet (Arunachal Pradesh)
  interior-points:
    base:
      - [77.54, 34.07] # Ladakh
    IND:
      - [74.95, 35.81] # Pakistani-Administered Kashmir
      - [77.54, 34.07] # Ladakh
      - [79.18, 35.15] # Aksai Chin
      - [76.32, 36.09] # Trans-Karakoram Tract
  exterior-points:
    base:
      - [74.95, 35.81] # Pakistani-Administered Kashmir
    CHN:
      - [79.18, 35.15] # Aksai Chin
      - [76.32, 36.09] # Trans-Karakoram Tract
    PAK:
      - [74.95, 35.81] # Pakistani-Administered Kashmir
      - [77.54, 34.07] # Ladakh

PAK:
  base:
    - [plus, relation, 307573] # Pakistan
  perspectives:
    PAK:
      # Pakistan's claims on "Indian-occupied Kashmir"
      - [plus, relation, 5515045] # Ladakh
      - [plus, relation, 1943188] # Jammu and Kashmir
      # Pakistan disclaims the Demchok sector, which is claimed by China
      - [minus, relation, 2713466] # Demchok sector
    IND:
      # India's claims on "Pakistan-occupied Kashmir"
      - [minus, relation, 13414393] # Pakistani-Administered Kashmir
  interior-points:
    CHN:
      - [74.95, 35.81] # Pakistani-Administered Kashmir
  exterior-points:
    base:
      - [77.54, 34.07] # Ladakh
