RUS:
  base:
    # Russia includes Crimea in OSM, but this is not widely acknowledged
    - [plus, relation, 60189] # Russia
    - [minus, relation, 3788824] # Crimea
  perspectives:
    RUS:
      - [plus, relation, 3788824] # Crimea
    UKR:
      - [minus, relation, 3788824] # Crimea

UKR:
  base:
    # Ukraine includes Crimea in OSM
    - [plus, relation, 60199] # Ukraine
  perspectives:
    RUS:
      - [minus, relation, 3788824] # Crimea
