CHN:
  base:
    - [plus, relation, 270056, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/270056.osm.xml.gz"] # China
  perspectives:
    CHN:
      # China's additional claims in the Sino-Indian border dispute
      - [plus, relation, 7935380, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/7935380.osm.xml.gz"] # Trans-Karakoram Tract
      - [plus, relation, 2713466, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713466.osm.xml.gz"] # Demchok sector
      - [plus, relation, 2713483, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713483.osm.xml.gz"] # Gue-Kaurik
      - [plus, relation, 2713485, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713485.osm.xml.gz"] # Shipki La
      - [plus, relation, 2713676, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713676.osm.xml.gz"] # Nilang-Jadhang
      - [plus, relation, 2713484, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713484.osm.xml.gz"] # Barahoti (Wu-Je)
      - [plus, relation, 3202329, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/3202329.osm.xml.gz"] # Arunachal Pradesh (South Tibet)
    IND:
      # India's claims in the Sino-Indian border dispute
      - [minus, relation, 7935380, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/7935380.osm.xml.gz"] # Trans-Karakoram Tract
      - [minus, relation, 2713465, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713465.osm.xml.gz"] # Aksai Chin
      - [minus, relation, 2713466, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713466.osm.xml.gz"] # Demchok sector
    PAK:
      # Pakistan disclaims the Demchok sector, which is claimed by China
      - [plus, relation, 2713466, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713466.osm.xml.gz"] # Demchok sector
  interior-points:
    base:
      # Points recognized to be administered by China
      - [79.18, 35.15] # Aksai Chin
      - [76.32, 36.09] # Trans-Karakoram Tract
      - [79.26, 33.11] # Eastern Demchock sector
    CHN:
      # Points claimed by China
      - [79.18, 35.15] # Aksai Chin
      - [76.32, 36.09] # Trans-Karakoram Tract
      - [79.26, 33.11] # Eastern Demchock sector
      - [79.35, 32.72] # Western Demchock sector
      - [94.47, 28.36] # South Tibet (Arunachal Pradesh)
  exterior-points:
    IND:
      # Points claimed by India
      - [79.26, 33.11] # Eastern Demchock sector
      - [79.35, 32.72] # Western Demchock sector
      - [94.47, 28.36] # Arunachal Pradesh (South Tibet)

IND:
  base:
    - [plus, relation, 304716, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/304716.osm.xml.gz"] # India
  perspectives:
    IND:
      # India's additional claims in the Sino-Indian border dispute
      - [plus, relation, 7935380, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/7935380.osm.xml.gz"] # Trans-Karakoram Tract
      - [plus, relation, 2713465, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713465.osm.xml.gz"] # Aksai Chin
      - [plus, relation, 2713466, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713466.osm.xml.gz"] # Demchok sector
      # India's claims on "Pakistan-occupied Kashmir"
      - [plus, relation, 13414393, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/13414393.osm.xml.gz"] # Pakistani-Administered Kashmir
    PAK:
      # Pakistan's claims on "Indian-occupied Kashmir"
      - [minus, relation, 5515045, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/5515045.osm.xml.gz"] # Ladakh
      - [minus, relation, 1943188, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/1943188.osm.xml.gz"] # Jammu and Kashmir
    CHN:
      # China's claims in the Sino-Indian border dispute
      - [minus, relation, 7935380, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/7935380.osm.xml.gz"] # Trans-Karakoram Tract
      - [minus, relation, 2713466, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713466.osm.xml.gz"] # Demchok sector
      - [minus, relation, 2713483, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713483.osm.xml.gz"] # Gue-Kaurik
      - [minus, relation, 2713485, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713485.osm.xml.gz"] # Shipki La
      - [minus, relation, 2713676, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713676.osm.xml.gz"] # Nilang-Jadhang
      - [minus, relation, 2713484, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713484.osm.xml.gz"] # Wu-Je (Barahoti)
      - [minus, relation, 3202329, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/3202329.osm.xml.gz"] # South Tibet (Arunachal Pradesh)
  interior-points:
    base:
      # Points recognized to be administered by India
      - [77.54, 34.07] # Ladakh
      - [79.35, 32.72] # Western Demchock sector
      - [94.47, 28.36] # Arunachal Pradesh (South Tibet)
    IND:
      # Points claimed by India
      - [74.95, 35.81] # Pakistani-Administered Kashmir
      - [77.54, 34.07] # Ladakh
      - [79.18, 35.15] # Aksai Chin
      - [76.32, 36.09] # Trans-Karakoram Tract
      - [79.26, 33.11] # Eastern Demchock sector
      - [79.35, 32.72] # Western Demchock sector
      - [94.47, 28.36] # Arunachal Pradesh (South Tibet)
  exterior-points:
    base:
      # Points recognized to be not administered by India
      - [74.95, 35.81] # Pakistani-Administered Kashmir
    CHN:
      # Points claimed by China
      - [79.18, 35.15] # Aksai Chin
      - [76.32, 36.09] # Trans-Karakoram Tract
      - [79.26, 33.11] # Eastern Demchock sector
      - [79.35, 32.72] # Western Demchock sector
      - [94.47, 28.36] # South Tibet (Arunachal Pradesh)
    PAK:
      # Points claimed by Pakistan
      - [74.95, 35.81] # Pakistani-Administered Kashmir
      - [77.54, 34.07] # Ladakh
      - [79.26, 33.11] # Eastern Demchock sector

PAK:
  base:
    - [plus, relation, 307573, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/307573.osm.xml.gz"] # Pakistan
  perspectives:
    PAK:
      # Pakistan's claims on "Indian-occupied Kashmir"
      - [plus, relation, 5515045, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/5515045.osm.xml.gz"] # Ladakh
      - [plus, relation, 1943188, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/1943188.osm.xml.gz"] # Jammu and Kashmir
      # Pakistan disclaims the Demchok sector, which is claimed by China
      - [minus, relation, 2713466, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/2713466.osm.xml.gz"] # Demchok sector
    IND:
      # India's claims on "Pakistan-occupied Kashmir"
      - [minus, relation, 13414393, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/13414393.osm.xml.gz"] # Pakistani-Administered Kashmir
  interior-points:
    base:
      # Points recognized to be administered by Pakistan
      - [74.95, 35.81] # Pakistani-Administered Kashmir
    PAK:
      # Points claimed by Pakistan
      - [77.54, 34.07] # Ladakh
    CHN:
      # Points claimed by China
      - [74.95, 35.81] # Pakistani-Administered Kashmir
  exterior-points:
    base:
      # Points recognized to be not administered by Pakistan
      - [77.54, 34.07] # Ladakh
    PAK:
      # Points disclaimed by Pakistan
      - [79.26, 33.11] # Eastern Demchock sector
      - [79.35, 32.72] # Western Demchock sector
