RUS:
  base:
    # Russia includes Crimea in OSM, but this is not widely acknowledged
    - [plus, relation, 60189, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/60189.osm.xml.gz"] # Russia
  perspectives:
    RUS:
      - [minus, relation, 3788824, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/3788824.osm.xml.gz"] # Crimea
    UKR:
      - [plus, relation, 3788824, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/3788824.osm.xml.gz"] # Crimea
  exterior-points:
    RUS:
      - [34.25, 45.41] # Crimea

UKR:
  base:
    # Ukraine includes Crimea in OSM
    - [plus, relation, 60199, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/60199.osm.xml.gz"] # Ukraine
    - [minus, relation, 3788824, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/3788824.osm.xml.gz"] # Crimea
  perspectives:
    RUS:
      - [plus, relation, 3788824, "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/3788824.osm.xml.gz"] # Crimea
  exterior-points:
    base:
      - [34.25, 45.41] # Crimea
  interior-points:
    RUS:
      - [34.25, 45.41] # Crimea
