RUS:
  base:
  - [plus, relation, 60189] # Russia (includes Crimea in OSM)
  - [minus, relation, 3788824] # Crimea is not widely acknowleged as part of Russia
  perspectives:
    RUS:
    - [plus, relation, 3788824] # Crimea
    UKR:
    - [minus, relation, 3788824] # Crimea

UKR:
  base:
  - [plus, relation, 60199] # Ukraine (includes Crimea in OSM)
  perspectives:
    RUS:
    - [minus, relation, 3788824] # Crimea
