CHN:
  base:
  - [plus, relation, 270056] # China
  perspectives:
    CHN:
    - [plus, relation, 7935380] # Trans-Karakoram Tract
    - [plus, relation, 2713466] # Demchok sector
    - [plus, relation, 2713483] # Gue-Kaurik
    - [plus, relation, 2713485] # Shipki La
    - [plus, relation, 2713676] # Nilang-Jadhang
    - [plus, relation, 2713484] # Barahoti (Wu-Je)
    - [plus, relation, 3202329] # Arunachal Pradesh (South Tibet)
    IND:
    - [minus, relation, 7935380] # Trans-Karakoram Tract
    - [minus, relation, 2713465] # Aksai Chin
    - [minus, relation, 2713466] # Demchok sector
    PAK:
    - [plus, relation, 2713466] # Demchok sector, touches PAK

IND:
  base:
  - [plus, relation, 304716] # India
  perspectives:
    IND:
    - [plus, relation, 13414393] # Pakistani-Administered Kashmir
    - [plus, relation, 7935380] # Trans-Karakoram Tract
    - [plus, relation, 2713465] # Aksai Chin
    - [plus, relation, 2713466] # Demchok sector
    PAK:
    - [minus, relation, 5515045] # Ladakh
    - [minus, relation, 1943188] # Jammu and Kashmir
    CHN:
    - [minus, relation, 7935380] # Trans-Karakoram Tract
    - [minus, relation, 2713466] # Demchok sector
    - [minus, relation, 2713483] # Gue-Kaurik
    - [minus, relation, 2713485] # Shipki La
    - [minus, relation, 2713676] # Nilang-Jadhang
    - [minus, relation, 2713484] # Wu-Je (Barahoti)
    - [minus, relation, 3202329] # South Tibet (Arunachal Pradesh)

PAK:
  base:
  - [plus, relation, 307573] # Pakistan
  perspectives:
    PAK:
    - [plus, relation, 5515045] # Ladakh
    - [plus, relation, 1943188] # Jammu and Kashmir
    - [minus, relation, 2713466] # Demchok sector, claimed by CHN
    IND:
    - [minus, relation, 13414393] # Pakistani-Administered Kashmir
