CHN:
  base:
  - [plus, relation, "fake-CHN", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-CHN.osm.xml.gz"]
  - [plus, relation, "fake-Trans-Karakoram-Tract", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Trans-Karakoram-Tract.osm.xml.gz"]
  perspectives:
    IND:
    - [minus, relation, "fake-Aksai-Chin", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Aksai-Chin.osm.xml.gz"]
    - [minus, relation, "fake-Trans-Karakoram-Tract", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Trans-Karakoram-Tract.osm.xml.gz"]
  interior-points:
    CHN:
      - [3.5, 2.5] # fake-Aksai-Chin
      - [3.7, 3.7] # fake-Trans-Karakoram-Tract

IND:
  base:
  - [plus, relation, "fake-IND", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-IND.osm.xml.gz"]
  - [minus, relation, "fake-Aksai-Chin", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Aksai-Chin.osm.xml.gz"]
  - [minus, relation, "fake-Trans-Karakoram-Tract", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Trans-Karakoram-Tract.osm.xml.gz"]
  perspectives:
    CHN:
    - [minus, relation, "fake-Aksai-Chin", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Aksai-Chin.osm.xml.gz"]
    - [minus, relation, "fake-Trans-Karakoram-Tract", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Trans-Karakoram-Tract.osm.xml.gz"]
    IND:
    - [plus, relation, "fake-PAK-Kashmir", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-PAK-Kashmir.osm.xml.gz"]
    - [plus, relation, "fake-Aksai-Chin", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Aksai-Chin.osm.xml.gz"]
    - [plus, relation, "fake-Trans-Karakoram-Tract", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Trans-Karakoram-Tract.osm.xml.gz"]
    PAK:
    - [minus, relation, "fake-IND-Kashmir", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-IND-Kashmir.osm.xml.gz"]
  interior-points:
    base:
      - [2.7, 2.3] # fake-IND-Kashmir
    IND:
      - [2.3, 2.7] # fake-PAK-Kashmir
      - [2.7, 2.3] # fake-IND-Kashmir
      - [3.5, 2.5] # fake-Aksai-Chin
      - [3.7, 3.7] # fake-Trans-Karakoram-Tract
  exterior-points:
    base:
      - [2.3, 2.7] # fake-PAK-Kashmir
    CHN:
      - [3.5, 2.5] # fake-Aksai-Chin
      - [3.7, 3.7] # fake-Trans-Karakoram-Tract
    PAK:
      - [2.3, 2.7] # fake-PAK-Kashmir
      - [2.7, 2.3] # fake-IND-Kashmir

PAK:
  base:
  - [plus, relation, "fake-PAK", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-PAK.osm.xml.gz"]
  perspectives:
    IND:
    - [minus, relation, "fake-PAK-Kashmir", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-PAK-Kashmir.osm.xml.gz"]
    PAK:
    - [plus, relation, "fake-IND-Kashmir", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-IND-Kashmir.osm.xml.gz"]
  interior-points:
    CHN:
      - [2.3, 2.7] # fake-PAK-Kashmir
  exterior-points:
    base:
      - [2.7, 2.3] # fake-IND-Kashmir

RUS:
  base:
  - [plus, relation, "fake-RUS", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-RUS.osm.xml.gz"]
  - [minus, relation, "fake-Crimea", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Crimea.osm.xml.gz"]
  perspectives:
    RUS:
    - [plus, relation, "fake-Crimea", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Crimea.osm.xml.gz"]
    UKR:
    - [minus, relation, "fake-Crimea", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Crimea.osm.xml.gz"]
  interior-points:
    RUS:
      - [-2.5, 1.5] # fake-Crimea

UKR:
  base:
  - [plus, relation, "fake-UKR", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-UKR.osm.xml.gz"]
  perspectives:
    RUS:
    - [minus, relation, "fake-Crimea", "https://github.com/migurski/political-multiviews/raw/cf219d1/data/sources/relation/fake-Crimea.osm.xml.gz"]
  interior-points:
    base:
      - [-2.5, 1.5] # fake-Crimea
  exterior-points:
    RUS:
      - [-2.5, 1.5] # fake-Crimea
