CHN:
  base:
  - [plus, relation, "fake-CHN"]
  - [plus, relation, "fake-Trans-Karakoram-Tract"]
  perspectives:
    IND:
    - [minus, relation, "fake-Aksai-Chin"]
    - [minus, relation, "fake-Trans-Karakoram-Tract"]
  interior-points:
    CHN:
      - [3.5, 2.5] # fake-Aksai-Chin
      - [3.7, 3.7] # fake-Trans-Karakoram-Tract

IND:
  base:
  - [plus, relation, "fake-IND"]
  - [minus, relation, "fake-Aksai-Chin"]
  - [minus, relation, "fake-Trans-Karakoram-Tract"]
  perspectives:
    CHN:
    - [minus, relation, "fake-Aksai-Chin"]
    - [minus, relation, "fake-Trans-Karakoram-Tract"]
    IND:
    - [plus, relation, "fake-PAK-Kashmir"]
    - [plus, relation, "fake-Aksai-Chin"]
    - [plus, relation, "fake-Trans-Karakoram-Tract"]
    PAK:
    - [minus, relation, "fake-IND-Kashmir"]
  interior-points:
    base:
      - [2.7, 2.3] # fake-IND-Kashmir
    IND:
      - [2.3, 2.7] # fake-PAK-Kashmir
      - [2.7, 2.3] # fake-IND-Kashmir
      - [3.5, 2.5] # fake-Aksai-Chin
      - [3.7, 3.7] # fake-Trans-Karakoram-Tract
  exterior-points:
    base:
      - [2.3, 2.7] # fake-PAK-Kashmir
    CHN:
      - [3.5, 2.5] # fake-Aksai-Chin
      - [3.7, 3.7] # fake-Trans-Karakoram-Tract
    PAK:
      - [2.3, 2.7] # fake-PAK-Kashmir
      - [2.7, 2.3] # fake-IND-Kashmir

PAK:
  base:
  - [plus, relation, "fake-PAK"]
  perspectives:
    IND:
    - [minus, relation, "fake-PAK-Kashmir"]
    PAK:
    - [plus, relation, "fake-IND-Kashmir"]
  interior-points:
    CHN:
      - [2.3, 2.7] # fake-PAK-Kashmir
  exterior-points:
    base:
      - [2.7, 2.3] # fake-IND-Kashmir

RUS:
  base:
  - [plus, relation, "fake-RUS"]
  - [minus, relation, "fake-Crimea"]
  perspectives:
    RUS:
    - [plus, relation, "fake-Crimea"]
    UKR:
    - [minus, relation, "fake-Crimea"]
  interior-points:
    RUS:
      - [-2.5, 1.5] # fake-Crimea

UKR:
  base:
  - [plus, relation, "fake-UKR"]
  perspectives:
    RUS:
    - [minus, relation, "fake-Crimea"]
  interior-points:
    base:
      - [-2.5, 1.5] # fake-Crimea
  exterior-points:
    RUS:
      - [-2.5, 1.5] # fake-Crimea
